# interface generated by SpecTcl version 1.1 from Z:/tmwgtwayTcl/da_cvs_Win.ui
#   root     is the parent window for this user interface

proc da_cvs_Win_ui {root args} {

  # this treats "." as a special case

  if {$root == "."} {
      set base ""
  } else {
      set base $root
  }

  text $base.text \
    -cursor {} \
    -height 1 \
    -width 1 \
    -xscrollcommand {list .scroll2 set} \
    -yscrollcommand {list .scroll set}
  catch {
    $base.text configure \
      -font {-*-MS Sans Serif-Medium-R-Normal-*-*-70-*-*-*-*-*-*}
  }

  scrollbar $base.scroll \
    -command {list .text yview} \
    -orient v

  label $base.label#1 \
    -justify right \
    -text TNS:
  catch {
    $base.label#1 configure \
      -font {-*-MS Sans Serif-Bold-R-Normal-*-*-80-*-*-*-*-*-*}
  }

  entry $base.entry#1 \
    -background yellow \
    -textvariable entryTNS

  label $base.label#2 \
    -justify right \
    -text Login:
  catch {
    $base.label#2 configure \
      -font {-*-MS Sans Serif-Bold-R-Normal-*-*-80-*-*-*-*-*-*}
  }

  entry $base.entry#2 \
    -background yellow \
    -textvariable entryLogin

  label $base.label#3 \
    -justify right \
    -text pass:
  catch {
    $base.label#3 configure \
      -font {-*-MS Sans Serif-Bold-R-Normal-*-*-80-*-*-*-*-*-*}
  }

  entry $base.entry#3 \
    -background yellow \
    -textvariable entryPswd

  label $base.label#4 \
    -justify right \
    -text Names:

  listbox $base.listbox \
    -height 0 \
    -width 0

  button $base.button#2 \
    -command daRun \
    -text Run

  label $base.label_A

  scrollbar $base.scroll2 \
    -orient h


  # Geometry management

  grid $base.text -in $root -row 1 -column 1  \
    -rowspan 10 \
    -sticky nesw
  grid $base.scroll -in $root -row 1 -column 2  \
    -rowspan 10 \
    -sticky nsw
  grid $base.label#1 -in $root  -row 1 -column 3  \
    -sticky nesw
  grid $base.entry#1 -in $root  -row 1 -column 4  \
    -sticky nesw
  grid $base.label#2 -in $root  -row 2 -column 3  \
    -sticky nesw
  grid $base.entry#2 -in $root  -row 2 -column 4  \
    -sticky nesw
  grid $base.label#3 -in $root  -row 3 -column 3  \
    -sticky nesw
  grid $base.entry#3 -in $root  -row 3 -column 4  \
    -sticky nesw
  grid $base.label#4 -in $root  -row 5 -column 3  \
    -sticky nesw
  grid $base.listbox -in $root  -row 5 -column 4  \
    -sticky nesw
  grid $base.button#2 -in $root -row 9 -column 4  \
    -sticky nesw
  grid $base.label_A -in $root  -row 10 -column 4  \
    -sticky new
  grid $base.scroll2 -in $root  -row 11 -column 1  \
    -sticky new

  # Resize behavior management

  grid rowconfigure $root 1 -weight 0 -minsize 16
  grid rowconfigure $root 2 -weight 0 -minsize 12
  grid rowconfigure $root 3 -weight 0 -minsize 8
  grid rowconfigure $root 4 -weight 0 -minsize 9
  grid rowconfigure $root 5 -weight 0 -minsize 9
  grid rowconfigure $root 6 -weight 0 -minsize 13
  grid rowconfigure $root 7 -weight 0 -minsize 14
  grid rowconfigure $root 8 -weight 0 -minsize 12
  grid rowconfigure $root 9 -weight 0 -minsize 30
  grid rowconfigure $root 10 -weight 1 -minsize 295
  grid rowconfigure $root 11 -weight 0 -minsize 2
  grid columnconfigure $root 1 -weight 1 -minsize 627
  grid columnconfigure $root 2 -weight 0 -minsize 14
  grid columnconfigure $root 3 -weight 0 -minsize 56
  grid columnconfigure $root 4 -weight 0 -minsize 2
# additional interface code
#####
#package require Tk
#####
global env

global entryTNS
global entryLogin
global entryPswd
global entryList


set entryTNS "rsdu2";
set entryLogin "rsduadmin" ;
set entryPswd "passme" ;
set entryList { Names Generic }


# This is a base-64-encoded animated GIF file.
set T4_data {
R0lGODlhQwA+APcAAAAAAAAAMwAAZgAAmQAAzAAA/wArAAArMwArZgArmQArzAAr/wBVAABVMwBV
ZgBVmQBVzABV/wCAAACAMwCAZgCAmQCAzACA/wCqAACqMwCqZgCqmQCqzACq/wDVAADVMwDVZgDV
mQDVzADV/wD/AAD/MwD/ZgD/mQD/zAD//zMAADMAMzMAZjMAmTMAzDMA/zMrADMrMzMrZjMrmTMr
zDMr/zNVADNVMzNVZjNVmTNVzDNV/zOAADOAMzOAZjOAmTOAzDOA/zOqADOqMzOqZjOqmTOqzDOq
/zPVADPVMzPVZjPVmTPVzDPV/zP/ADP/MzP/ZjP/mTP/zDP//2YAAGYAM2YAZmYAmWYAzGYA/2Yr
AGYrM2YrZmYrmWYrzGYr/2ZVAGZVM2ZVZmZVmWZVzGZV/2aAAGaAM2aAZmaAmWaAzGaA/2aqAGaq
M2aqZmaqmWaqzGaq/2bVAGbVM2bVZmbVmWbVzGbV/2b/AGb/M2b/Zmb/mWb/zGb//5kAAJkAM5kA
ZpkAmZkAzJkA/5krAJkrM5krZpkrmZkrzJkr/5lVAJlVM5lVZplVmZlVzJlV/5mAAJmAM5mAZpmA
mZmAzJmA/5mqAJmqM5mqZpmqmZmqzJmq/5nVAJnVM5nVZpnVmZnVzJnV/5n/AJn/M5n/Zpn/mZn/
zJn//8wAAMwAM8wAZswAmcwAzMwA/8wrAMwrM8wrZswrmcwrzMwr/8xVAMxVM8xVZsxVmcxVzMxV
/8yAAMyAM8yAZsyAmcyAzMyA/8yqAMyqM8yqZsyqmcyqzMyq/8zVAMzVM8zVZszVmczVzMzV/8z/
AMz/M8z/Zsz/mcz/zMz///8AAP8AM/8AZv8Amf8AzP8A//8rAP8rM/8rZv8rmf8rzP8r//9VAP9V
M/9VZv9Vmf9VzP9V//+AAP+AM/+AZv+Amf+AzP+A//+qAP+qM/+qZv+qmf+qzP+q///VAP/VM//V
Zv/Vmf/VzP/V////AP//M///Zv//mf//zP///wAAAAAAAAAAAAAAACH5BAEAAPwALAAAAABDAD4A
AAj/APcJHEiwoMGDCBMqXMiwocOHECNKnEixosWLGDNWJJYmB44cMjzO+BgSx0iQIkmmRGlSZUuP
Y9Ioq6hM05gxLXOO1ImDp8+dQHueHKNp2URiCGQ4kDFyhgyTT51CnSq1atSrVKPikIEAh1GImrqy
fMqTZVCzQl2e1TpSwEyHxKi2bNpSa8i7W0HO3VoXJVu+I2V8XQiKUteRCfgmDnkYBwK9i3M0fvw0
8mS9lPXK0ESMYRqcgfcG9qt3NF7TfvveLW3SwZg3DEk6oBua7um8t22zXv0U7+IxORjuxpEY8dbZ
jkEip0z8+EjKyGcs3frgdkkZsXlrxp2aNnfr3ffK/6jel2HtpaR7h7eruu7375C3xtY9/m51zayl
N0WunXH8+mmdxBBj7uFln39K1QYYeo39hVpXdwmnlUke8YbbhfSFVxyGHI40X0uRKUVaXhdKVqFe
Ofl2YYh6BbeQgta1lJmFdyG34Wh5ifVXhAs1Jx2BTs2GngxK1TdkiFslmByRfhF4GHoDthcUXjmg
dt2Ipn0EYUr0eRbTl5+FCeaYYpZJ5plmhqmmRmy26eabcMb5kCZ00kkMnQNFc2eddL61zzJ88qmM
Mnf6KVBNnVV0Ew44wZTGMspkAhyjlI5BiUCaiIHTpowSlUkOYxC0TEdpWITeTZ85pskkI900xg+T
4v+gyT6afATqq2M8VtNHswo0yUeJUrRVrwKpIcMkY7hWEDE4zRrWJNAQFNJMhmH3J0ilWjQDAsHS
ikNHMmSLkCYyqEHPQMogMMZMyiR7aRrhDiZsuHRmQi4CmqSBgLgH1fponiElqgyR5MqKEWZccbUu
vKEWBGk9+8BLSbQC0aPrQGENm5FjatzpMbXqRkOQMp/NChKx+0Qz7UD0SJZGtxURfFBHjKZh82dP
rZpUTJPYPMZTlMyUb0goW5RDDjAfOgmoHzWaQ9BiHd300UTrefQkbGqSibwE6WmnncpAs0xImeyp
NWfA7oOonBANnAPEBqXN9kSTFI0xMRTPrXdFNvf/nIbfgKvxd9+E9y144X6rIYw887Ajz+OPOy6P
5JPPI09sR2euuUecd+75R6BLnbkMwqxj+umoB4P66QMS6frrTL3uFJGzx2677cSprk48wUyOTDyO
xzP5MabHs86HnIfeU/Iv9QS68h7htovq68xDTz7W62N9Ptevo47qEm5VO0izO1Va7OW7bv5dCVAv
Tz4J6aMO6z0S6NFiODwg1JA4OBB98pybjDDmt45z7UMf+rgePRJIj2Ds7ngvmsuOstQUIiWASJSx
i2RUF4x46EMg7VAHMNRBjhES0HThm5JoctSi5VVGNe0zHTvmIZB5WO+A2vPeOogXpR+ZCED12U4F
/8Njml14730IQeAJP0QfKe2lQZqxUTCIFwwD7sOGCRyI6eY3ICHCR0k/Eg9KmLMt6q3jcZY7YwEH
Io8OQlAhJLnPX3SUn76QEURGPOE6HLgOYFxOIPIgoJdwQ54ZtYc5+MNRSKh3DMY97nQ0FAg7THcM
hnDkjhRkYW7Eg5jpqWMeHwTkGa1IPC4ypGA4Gk2D2nMl5GwlhqaL5EHkVzy4IAA6mdxQSfRzIa3E
cH4znOXqHBINcqkIPJRpkBx/KINgqC4ewDCdPBbHDuPtcX7HUAdEOAKck+zSJSXh0nsSULrTWfN0
ZjxnRDTxBjGsBHTefGfnQgeSZ6LTePgsnj73xgXPfmokIAA7
}

image create photo T4_data -data $T4_data
$base.label_A configure -image T4_data

catch { $base.listbox configure -listvariable entryList }
$base.listbox activate 1
$base.listbox selection anchor 1

catch {
$base.text configure -yscrollcommand [list $base.scroll set] -setgrid 1 \
  -height 30 -undo 1 -autosep 1 \
        -xscrollcommand [list $base.scroll2 set]
}

$base.scroll configure -command [list $base.text yview]
$base.scroll2 configure -command [list $base.text xview]

update


proc daRun { } {
global tcl_platform
#
global entryTNS
global entryLogin
global entryPswd
global entryList

#
set f "da_dev.tcl"
set paths [info script]
set paths [ file normalize $paths ]
set dirname [ file dirname $paths ]
set f0 [file join $dirname $f ]
set f [ file nativename $f0 ]
#
source $f

set tns $entryTNS
set usr $entryLogin
set pwd $entryPswd
set crn [.listbox curselection ]
if {$crn==""} { set crn 1 ;}


  catch { .text delete 1.0 end ;  }

  set t1 [ clock format [ clock seconds ] -format "%T" ]
  set s1 "start = $t1"
  .text insert 0.0 "\n--------------------------------------\n"
  .text insert end "\nstart = $t1\n"

  set ls {};
  tmwgtway $tns $usr $pwd $crn ls

  for {set ind 0} {$ind<[llength $ls]} {incr ind} {
      .text insert end "[lindex $ls $ind ]\n" ;
  }

  set t1 [ clock format [ clock seconds ] -format "%T" ]
  .text insert end "\nend = $t1\n"

 .text mark set insert 0.0

 update;

 return 0 ;
}
































# end additional interface code

}


# Allow interface to be run "stand-alone" for testing

catch {
    if [info exists embed_args] {
  # we are running in the plugin
  da_cvs_Win_ui .
    } else {
  # we are running in stand-alone mode
  if {$argv0 == [info script]} {
      wm title . "Testing da_cvs_Win_ui"
      da_cvs_Win_ui .
  }
    }
}
