# interface generated by SpecTcl version 1.1 from R:/winui.ui
#   root     is the parent window for this user interface

proc winui_ui {root args} {

	# this treats "." as a special case

	if {$root == "."} {
	    set base ""
	} else {
	    set base $root
	}
    
	text $base.text#1 \
		-height 1 \
		-width 1

	button $base.button#1 \
		-text ok


	# Geometry management

	grid $base.text#1 -in $root	-row 1 -column 2  \
		-sticky nesw
	grid $base.button#1 -in $root	-row 2 -column 2 

	# Resize behavior management

	grid rowconfigure $root 1 -weight 1 -minsize 188
	grid rowconfigure $root 2 -weight 0 -minsize 30
	grid columnconfigure $root 1 -weight 0 -minsize 30
	grid columnconfigure $root 2 -weight 1 -minsize 382
	grid columnconfigure $root 3 -weight 0 -minsize 30
# additional interface code
# end additional interface code

}


# Allow interface to be run "stand-alone" for testing
winui_ui .
catch {
    if [info exists embed_args] {
	# we are running in the plugin
	winui_ui .
    } else {
	# we are running in stand-alone mode
	if {$argv0 == [info script]} {
	    wm title . "Testing winui_ui"
	    winui_ui .
	}
    }
}
